version: '3'
services:
  extension-module:
    env_file:
      - .env
    build:
      context: ./extension
    ports:
      - ${EXTENSION_MODULE_PORT}:8080
    restart: unless-stopped
  notification-module:
    env_file:
      - .env
    build:
      context: ./notification
    ports:
      - ${NOTIFICATION_MODULE_PORT}:8080
    restart: unless-stopped